name: Build Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Restore cached files
      uses: actions/cache@v4
      with:
        path: |
          Tools/FE-PyTools
          Tools/EventAssembler
          encrypt_0x55_fe8u.bin
        key: cache-${{ runner.os }}-${{ hashFiles('dependencies.lock') }}

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-arm-none-eabi gcc-arm-none-eabi build-essential cmake
        sudo apt-get install -y re2c ghc cabal-install libghc-vector-dev libghc-juicypixels-dev
        sudo apt-get install -y python3-pip pkg-config libpng* moreutils unzip
        python3 -m pip install --upgrade pip
        python3 -m pip install pyelftools PyInstaller tmx six Pillow

    - name: Install DEVKITPRO
      run: |
        curl -L -o devkit.gz https://github.com/MokhaLeee/fe8_hacks_sundries/releases/download/ci/devkit.gz
        tar -xzvf devkit.gz -C $HOME/

        echo "DEVKITPRO=$HOME/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=\${DEVKITPRO}/devkitARM" >> $GITHUB_ENV
        echo "DEVKITPPC=\${DEVKITPRO}/devkitPPC" >> $GITHUB_ENV
        echo "\${DEVKITPRO}/tools/bin" >> $GITHUB_PATH

    - name: Install submodules
      run: |
        git clone https://github.com/MokhaLeee/FE-CLib-Mokha.git Tools/FE-CLib-Mokha

        if [ ! -d Tools/FE-PyTools/ ]; then
          git clone https://github.com/StanHash/FE-PyTools.git --recursive Tools/FE-PyTools
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Build EA
      run: |
        if [ ! -d Tools/EventAssembler/ ]; then
          cd Tools && wget https://github.com/MokhaLeee/EventAssembler/releases/download/prebuild/EventAssembler.zip
          unzip EventAssembler.zip
          cd ..
        fi

    - name: Fake generate baserom
      run: |
        if [ ! -e encrypt_0x55_fe8u.bin ]; then
          wget https://github.com/MokhaLeee/fe8_hacks_sundries/releases/download/ci_/encrypt_0x55_fe8u.bin
        fi
        python3 Tools/scripts/encrypt/decrypt.py encrypt_0x55_fe8u.bin fe8.gba 0x55

    - name: Debug remove skill build
      run: make -j CONFIG_CI_NO_SKILL_TEST=1

    - name: Clean build
      run: make clean

    - name: release build
      run: make -j CONFIG_RELEASE_COMPILATION=1

    - name: post build
      run: |
        echo "BUILD_TIME=$(date +"%Y%m%d.%H")" >> $GITHUB_ENV
        ./Tools/scripts/generate_release.sh
        rm -f .release_dir/*.gba

    - uses: actions/upload-artifact@v4.3.5
      with:
        name: ${{ github.event.repository.name }}-${{ env.BUILD_TIME }}
        path: |
          .release_dir/*
        retention-days: 1
